### ISSUE TITLE
vue ui: ERROR  Failed fetching remote preset

### ISSUE THREAD

**Issue by jeeinn** [vuejs/vue#10218]
### Version
2.6.10

### Reproduction link
[https://github.com/youzan/vant-demo](https://github.com/youzan/vant-demo)

### Steps to reproduce
Opening E:\Project\nodejs\hello-world...
-  Fetching remote preset git@github.com:youzan/vant-demo.git...
✔  Fetching remote preset git@github.com:youzan/vant-demo.git...
 ERROR  Failed fetching remote preset git@github.com:youzan/vant-demo.git:
Error: 'git clone' failed with status 128
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\git-clone\index.js:33:22)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:606:12)
TypeError: Cannot read property 'indexOf' of undefined
    at progress.wrap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\projects.js:274:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### What is expected?
弹出无预置方案，提示错误

### What is actually happening?
ui 直接 hang 住了

---
出错后 ui 直接 hang 住了，能不能友好捕捉并弹出提示错误

**Comment by Justineo** [comment]
Hi, thanks for reporting.

Please file this issue in the repo of [Vue CLI](https://github.com/vuejs/vue-cli), because this seems to be a problem of Vue CLI UI.
