### ISSUE TITLE
Allow devs to specify port when running `npm test`

### ISSUE THREAD

**Issue by warmsocks** [vuejs/vue#11482]
### What problem does this feature solve?
When I was testing a fix for #11480, I wasn't able to complete `npm test` apparently because I already had a GitLab instance running which is listening on port 8080, and I didn't want to take it down.  (If there is already a way to specify an alternate port I didn't see it, and it should be documented).

The test failed as follows.  Successfully passed tests are removed for brevity.

```
vue (spelling-fixes-warmsocks *=) $ npm test
> vue@2.6.11 test /home/scase/vue
> npm run lint && flow check && npm run test:types && npm run test:cover && npm run test:e2e -- --env phantomjs && npm run test:ssr && npm run test:weex

 # passed tests ...

> vue@2.6.11 test:e2e /home/scase/vue
> npm run build -- web-full-prod,web-server-basic-renderer && node test/e2e/runner.js "--env" "phantomjs"


> vue@2.6.11 build /home/scase/vue
> node scripts/build.js "web-full-prod,web-server-basic-renderer"

dist/vue.min.js 91.44kb (gzipped: 33.30kb)
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at HttpServer.listen (/home/scase/vue/node_modules/http-server/lib/http-server.js:138:22)
    at Object.<anonymous> (/home/scase/vue/test/e2e/runner.js:8:8)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8080
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue@2.6.11 test:e2e: `npm run build -- web-full-prod,web-server-basic-renderer && node test/e2e/runner.js "--env" "phantomjs"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue@2.6.11 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scase/.npm/_logs/2020-07-01T00_33_12_846Z-debug.log
npm ERR! Test failed.  See above for more details.
```

### What does the proposed API look like?
First, document the feature:

```bash
    $ npm test --help

    npm test [--port <number>] [-- <args>] 

    aliases: tst, t
```

Second, provide a suggestion when the issue is hit, as in this pseudo code change to test/e2e/runner.js:
```javascript
    try {
        server.listen(server_port)
    }
    catch (err) {
         if (err is EADDRINUSE) {
            throw "Port "   server_port   " is already in use.  You can change it by doing npm test --port <portnumber>"
        }
        else  { 
            throw err;
        }
    }
```
Third, implement the feature.  The command line:
```bash
    $ npm test --port 8111
```

I tried the above, and at first glance it looked to me like it was going to work:
 ```bash
3sc3396:/home/scase/vue (dev *=) $ npm test --port 8111

> vue@2.6.11 test /home/scase/vue
> npm run lint && flow check && npm run test:types && npm run test:cover && npm run test:e2e -- --env phantomjs && npm run test:ssr && npm run test:weex "8111"
```
... but it eventually failed the same way as in the problem description. 

I found these hard-coded port numbers in `test/` which may have to change:
```
3sc3396:/home/scase/vue (dev *=) $ grep -r -i 8080 test
test/e2e/runner.js:server.listen(8080)
test/e2e/specs/commits.js:    .url('http://localhost:8080/examples/commits/')
test/e2e/specs/todomvc.js:    .url('http://localhost:8080/examples/todomvc/#test')
test/e2e/specs/todomvc.js:    browser.url('http://localhost:8080/examples/todomvc/#active')
test/e2e/specs/todomvc.js:    browser.url('http://localhost:8080/examples/todomvc/#completed')
test/e2e/specs/async-edge-cases.js:    .url('http://localhost:8080/test/e2e/specs/async-edge-cases.html')
test/e2e/specs/modal.js:    .url('http://localhost:8080/examples/modal/')
test/e2e/specs/grid.js:    .url('http://localhost:8080/examples/grid/')
test/e2e/specs/basic-ssr.js:    .url('http://localhost:8080/test/e2e/specs/basic-ssr.html')
test/e2e/specs/markdown.js:    .url('http://localhost:8080/examples/markdown/')
test/e2e/specs/svg.js:    .url('http://localhost:8080/examples/svg/')
test/e2e/specs/select2.js:    .url('http://localhost:8080/examples/select2/')
test/e2e/specs/tree.js:    .url('http://localhost:8080/examples/tree/')
```

This would allow casual contributors to run a complete test cycle more easily without disrupting anything they may have set up already.

**Comment by posva** [comment]
As with the other issue, these are for big reports and feature requests only. Feel free to take a stab and try implementing specifying the port and submitting a pull request!
