### ISSUE TITLE
Transition removes components but allows interaction before transition is done, causing errors

### ISSUE THREAD

**Issue by srchulo** [vuejs/vue#11580]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-select-comparison-io8jv?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/vue-select-comparison-io8jv?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. Click select menu
2. Click an item
3. Keep clicking items while the transition fades
4. Check console

### What is expected?
Clicking the transitioning item shouldn't cause errors

### What is actually happening?
Clicking the transitioning item causes errors that can be seen in the console.

---
I think that the component is removed and it's state and state of subcomponents are removed/cleaned up, which can cause bugs. Here's the error that I see in my example:

```
TypeError: Cannot read property 'blur' of undefined
    at VueComponent.onAfterSelect (https://pf90u.csb.app/node_modules/vue-select/dist/vue-select.js:1:11729)

    at VueComponent.select (https://pf90u.csb.app/node_modules/vue-select/dist/vue-select.js:1:11260)

    at mousedown (https://pf90u.csb.app/node_modules/vue-select/dist/vue-select.js:2:1026)

    at invokeWithErrorHandling (eval at Eo (https://codesandbox.io/static/js/sandbox.50c3e4cdd.js:1:201658), <anonymous>:1859:26)

    at HTMLAnchorElement.invoker (eval at Eo (https://codesandbox.io/static/js/sandbox.50c3e4cdd.js:1:201658), <anonymous>:2184:14)

    at HTMLAnchorElement.original._wrapper (eval at Eo (https://codesandbox.io/static/js/sandbox.50c3e4cdd.js:1:201658), <anonymous>:7543:25)
```

And here's the error that I was seeing locally, but was unable to reproduce in my above example (but I believe that it's the same root cause):

```
client.js?06a0:97 TypeError: Cannot read property 'contains' of undefined
    at eval (vue-select.js?4a7a:1)
    at Array.some (<anonymous>)
    at VueComponent.toggleDropdown (vue-select.js?4a7a:1)
    at mousedown (vue-select.js?4a7a:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLDivElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLDivElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)
```

And the above corresponds to this line:

https://github.com/sagalbot/vue-select/blob/2615fa1411df4bc830e2cdd5ea61389b4814123b/src/components/Select.vue#L750

My example uses vue-select, but I believe this is a Vue transition error that could apply to other components.

**Comment by posva** [comment]
Please open a new issue with no external dependencies as this could come from vue select
