### ISSUE TITLE
Unexpected token in createComponentInstanceForVnode when running dev

### ISSUE THREAD

**Issue by mitchellbryson** [vuejs/vue#11703]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/dist/vue.esm.browser.js#L3300](https://github.com/vuejs/vue/blob/dev/dist/vue.esm.browser.js#L3300)

### Steps to reproduce
1. Clone the repo
2. Run `yarn install`
3. Run `yarn run dev`

### What is expected?
Should bundle without errors

### What is actually happening?
Error: Unexpected token

---
````
src/core/vdom/create-component.js (214:4)
212:   const options: InternalComponentOptions = {
213:     _isComponent: true,
214:     _parentVnode: vnode,
         ^
215:     parent
216:   }
Error: Unexpected token
    at error (/Users/mitchellbryson/Dropbox/personal/vue/node_modules/rollup/dist/rollup.js:3599:30)
    at Module.error (/Users/mitchellbryson/Dropbox/personal/vue/node_modules/rollup/dist/rollup.js:14374:9)
    at tryParse (/Users/mitchellbryson/Dropbox/personal/vue/node_modules/rollup/dist/rollup.js:14037:16)
    at Module.setSource (/Users/mitchellbryson/Dropbox/personal/vue/node_modules/rollup/dist/rollup.js:14093:35)
    at /Users/mitchellbryson/Dropbox/personal/vue/node_modules/rollup/dist/rollup.js:17456:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 2)
    at async Promise.all (index 1)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
````

**Comment by mitchellbryson** [comment]
I think this is due to line #210 that recently had the trailing comma removed. The unexpected token seems to be the comment on this line. Removing the comment works fine.

**Comment by midnight-dev** [comment]
Sorry to bump this well over a month after it was addressed, but can the build process really not cope with same-line comments?

I see this was fixed by moving the comments to separate preceding lines. So is this is a practice that should always be observed for development of VueJS, or was this a quirky edge-case that doesn't warrant further investigation?
