### ISSUE TITLE
npm test fails on Windows

### ISSUE THREAD

**Issue by ygj6** [vuejs/vue#11782]
### Version
2.6.11

### Reproduction link
[https://github.com/vuejs/vue/blob/dev/package.json](https://github.com/vuejs/vue/blob/dev/package.json)

### Steps to reproduce
After cloning the vue repo, run the following command
```
yarn
npm test
```

### What is expected?
All the test cases passed

### What is actually happening?
Failed at the vue@2.6.12 test:e2e script.
```
Running:  commits
 × Timed out while waiting for element <li> to be present for 5000 milliseconds.  - expected "visible" but got: "not found"
    at Object.commits (D:\git\vue\test\e2e\specs\commits.js:5:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

FAILED:  1 assertions failed (8.121s)
```

---
My OS version is windows 10 and node version is v12.16.1

**Comment by ygj6** [comment]
Hi @posva, it seems that the http-server didn't response correctly. After I upgrade the http-server to the latest version, the problem solved.
