### ISSUE TITLE
VUE 3  SSR - Error (500) [vuex] do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by murilolivorato** [vuejs/vue#12437]
### Version
3.0

### Reproduction link
[github.com](https://github.com/murilolivorato/quasar_2_test_ssr)

### Steps to reproduce
Hello , I am working with Quasar 2 + vue 3 . it is giving me an error .
ONLY IF I REFRESH THE PAGE ( IN SSR MODE ) - 

```
Error (500)
[vuex] do not mutate vuex store state outside mutation handlers.
```
I did a new project , and I made a few lines of code calling VUEX , and it giving me this error when I refresh .
I added the code on git -
https://github.com/murilolivorato/quasar_2_test_ssr

here is the image of the error -
https://ibb.co/CKgLB6B

BUT, only appears this error if you try to refresh the page .
sometimes , you need to refresh the page 3 times .
Then, the error , appears .

### What is expected?
I expect stop giving this error when refresh the page

### What is actually happening?
error in SSR mode when refresh the page

---

this is my code - 
HOME.JS
```
import { mapGetters } from 'vuex'
export default {
  name: 'Home',
  methods: {
    loadPage () {
      Promise.all([
        // RESET FILTERS
        this.$store.dispatch('home/set_panel_result', true),
        // RESET FILTERS
        this.$store.dispatch('home/set_component_is_loaded', false)
      ]).then((res) => {
        // RESET FILTERS
        console.log('ok ')
        this.$store.dispatch('home/set_component_is_loaded', true)
      })
    }
  },
  computed: {
    ...mapGetters('home', {
      componentIsLoaded: 'componentIsLoaded'
    })
  },
  created () {
    this.loadPage()
  }
}
```
VUEX
```
const state = {
  // SEARCH RESULT
  searchResult: { sell: [{ value: null, showResult: false }], rent: [{ value: null, showResult: false }] },
  // COMPONENT IS LOADED
  componentIsLoaded: false
}
const mutations = {
  'SET_COMPONENT_IS_LOADED' (state, data) {
    state.componentIsLoaded = data;
  },
  'SET_PANEL_RESULT' (state, data) {
    state.componentIsLoaded = data;
  }
}
const actions = {
  set_panel_result: ({ commit }, data) => {
    commit('SET_PANEL_RESULT', data)
  },
  set_component_is_loaded: ({ commit }, data) => {
    commit('SET_COMPONENT_IS_LOADED', data)
  }
}
const getters = {
  // COMPONENT IS LOADED
  componentIsLoaded: state => {
    return state.componentIsLoaded
  }
}

export default {
  namespaced: true,
  state,
  mutations,
  actions,
  getters
}
```
ERROR ON CONSOLE  WHEN REFRESH THE PAGE-

```
[Quasar Dev Webserver] / -> request took: 1664ms
[Vue warn]: Unhandled error during execution of watcher callback
[Vue warn]: Unhandled error during execution of created hook 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
[Quasar Dev Webserver] / -> error during render
Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (/home/cidinha/Docker/quasar_2_test/node_modules/vuex/dist/vuex.cjs.js:85:27)
    at vue.watch.deep (/home/cidinha/Docker/quasar_2_test/node_modules/vuex/dist/vuex.cjs.js:349:7)
    at callWithErrorHandling (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at callWithAsyncErrorHandling (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
    at ReactiveEffect.job [as scheduler] (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1770:17)
    at triggerEffects (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/reactivity/dist/reactivity.cjs.js:354:24)
    at trigger (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/reactivity/dist/reactivity.cjs.js:330:17)
    at Object.set (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/reactivity/dist/reactivity.cjs.js:479:17)
    at Store.SET_COMPONENT_IS_LOADED (render-app.js:487:29)
    at wrappedMutationHandler (/home/cidinha/Docker/quasar_2_test/node_modules/vuex/dist/vuex.cjs.js:300:13)
[Vue warn]: Unhandled error during execution of watcher callback
[Vue warn]: Unhandled error during execution of created hook 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
[Quasar Dev Webserver] / -> error during render
Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (/home/cidinha/Docker/quasar_2_test/node_modules/vuex/dist/vuex.cjs.js:85:27)
    at vue.watch.deep (/home/cidinha/Docker/quasar_2_test/node_modules/vuex/dist/vuex.cjs.js:349:7)
    at callWithErrorHandling (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at callWithAsyncErrorHandling (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
    at ReactiveEffect.job [as scheduler] (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1770:17)
    at triggerEffects (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/reactivity/dist/reactivity.cjs.js:354:24)
    at trigger (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/reactivity/dist/reactivity.cjs.js:330:17)
    at Object.set (/home/cidinha/Docker/quasar_2_test/node_modules/@vue/reactivity/dist/reactivity.cjs.js:479:17)
    at Store.SET_PANEL_RESULT (render-app.js:491:29)
    at wrappedMutationHandler (/home/cidinha/Docker/quasar_2_test/node_modules/vuex/dist/vuex.cjs.js:300:13)

```

**Comment by LinusBorg** [comment]
1. The Vue 3 repo lives here: https://github.com/vuejs/core
2. You should first open an issue with the Quasar project if their SSR implementation causes this issue. We won't have the capacity to debug issues within large framework built in top of Vue.
