### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Sakura0408** [vuejs/vue#12567]
### Version
2.6.14

### Reproduction link
[github.com](https://github.com/Sakura0408/require-test.git)

### Steps to reproduce
1. npm install & npm run dev
2. open browser, error messages can be viewed in the console tab of Chrome DevTools
3. not only screenfull.js will have this problem, sheetjs also

### What is expected?
can be imported correctly

### What is actually happening?
![image](https://user-images.githubusercontent.com/42940527/174731440-3b3cfcdf-f766-45c5-80b6-f1396a0599da.png)

```
ReferenceError: require is not defined
    at eval (index.js:4:30)
    at ./node_modules/screenfull/index.js (chunk-vendors.js:9667:1)
    at __webpack_require__ (app.js:5894:33)
    at fn (app.js:6145:21)
    at eval (index.vue?bbc8:27:1)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/scada/runtime/index.vue?vue&type=script&lang=js& (app.js:3469:1)
    at __webpack_require__ (app.js:5894:33)
    at fn (app.js:6145:21)
    at eval (index.vue?vue&type=script&lang=js&:5:229)
    at ./src/views/scada/runtime/index.vue?vue&type=script&lang=js& (app.js:1702:1)
```

**Comment by Sakura0408** [comment]
> I tested it and there is no error

I retried removing the configureWebpack option on my work computer, it didn't work, the error still appears

**Comment by Sakura0408** [comment]
> I tested it and there is no error

Ok, i remove transpileDependencies option, it work
