### ISSUE TITLE
ERR_INVALID_ARG_TYPE when upgrade Vue 2.6.14 to 2.7.8

### ISSUE THREAD

**Issue by Emuzex** [vuejs/vue#12692]
### Version
2.7.8

### Reproduction link
I can't link a repo because that is on local network

### Steps to reproduce
Just follow the upgrade guide steps from this page: https://blog.vuejs.org/posts/vue-2-7-naruto.html

### What is expected?
Upgrade without error

### What is actually happening?
After npm install, i got an error message, but i can start development process and the new vue version works so far.

Here is the npm install debug log: 
```
70 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
70 verbose stack     at open (node:fs:546:10)
70 verbose stack     at go$open (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:357:14)
70 verbose stack     at Object.open (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:354:12)
70 verbose stack     at writeFile (node:fs:2137:6)
70 verbose stack     at go$writeFile (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:138:14)
70 verbose stack     at writeFile (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:135:12)
70 verbose stack     at node:internal/util:360:7
70 verbose stack     at new Promise (<anonymous>)
70 verbose stack     at writeFile (node:internal/util:346:12)
70 verbose stack     at Shrinkwrap.save (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/shrinkwrap.js:1136:7)
71 verbose cwd /var/www/html
72 verbose Linux 5.15.55-1-MANJARO
73 verbose node v16.16.0
74 verbose npm  v8.15.0
75 error code ERR_INVALID_ARG_TYPE
76 error The "path" argument must be of type string or an instance of Buffer or URL. Received null
```

---
Full stak is Laravel (webpack mix) with Vue 2, run in docker with sail in development.

**Comment by posva** [comment]
Looking at the stacktrace, the error comes from `@npmcli/arborist`, not from vue. It seems to be harmless as it concerns the logging only though.
