### ISSUE TITLE
vue.runtime.esm.js:2872 Uncaught (in promise) TypeError: Cannot read properties of null (reading '$vnode')

### ISSUE THREAD

**Issue by angleyu** [vuejs/vue#12782]
### Version
2.7.0

### Reproduction link
[github.com](https://github.com/vuejs/vue/tree/v2.7.0)

### Steps to reproduce
 Modal.confirm({
        title: h('div', {class: 'titlebox'}, [
          h('span', {class: 'block center-title'}, '温馨提醒'),
        ]),
        icon: 'none',
        content: h(
          'div',
          {class: 'confirm-con'},
          '内容',
        ),
        class: 'hintwrap dialogClass confirm',
        okText: '确认',
        centered: true,
        cancelText: '我再想想',}
ant 使用的是^1.7.8版本

### What is expected?
To solve

### What is actually happening?
vue.runtime.esm.js:2872 Uncaught (in promise) TypeError: Cannot read properties of null (reading '$vnode')
    at _createElement (vue.runtime.esm.js:2872:23)
    at createElement$1 (vue.runtime.esm.js:2836:12)
    at h (vue.runtime.esm.js:2952:12)
    at handleHintModal (ChapterDetail.vue:704:42)
    at handleOptionChapter (ChapterDetail.vue:724:5)
    at invokeWithErrorHandling (vue.runtime.esm.js:2987:30)
    at VueComponent.invoker (vue.runtime.esm.js:1785:20)
    at invokeWithErrorHandling (vue.runtime.esm.js:2987:30)
    at Vue2.$emit (vue.runtime.esm.js:3685:17)
    at VueComponent.handleClick2 (button.js:124:12)
_createElement @ vue.runtime.esm.js:2872
createElement$1 @ vue.runtime.esm.js:2836
h @ vue.runtime.esm.js:2952
handleHintModal @ ChapterDetail.vue:704
handleOptionChapter @ ChapterDetail.vue:724
invokeWithErrorHandling @ vue.runtime.esm.js:2987
invoker @ vue.runtime.esm.js:1785
invokeWithErrorHandling @ vue.runtime.esm.js:2987
Vue2.$emit @ vue.runtime.esm.js:3685
handleClick2 @ button.js:124
invokeWithErrorHandling @ vue.runtime.esm.js:2987
invoker @ vue.runtime.esm.js:1785
original_1._wrapper @ vue.runtime.esm.js:7428

**Comment by Justineo** [comment]
Please provide a minimal reproduction.
