### ISSUE TITLE
webpack编译报错, this._init is not a function， /vue.common.js

### ISSUE THREAD

**Issue by ivan403704409** [vuejs/vue#2194]
ERROR in ./src/components/loading.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue (/Users/ivan.liu/VIP文件/file/VIP-GULP/Project/git/vue-webpack/node_modules/vue/dist/vue.common.js:9095:8)
 @ ./src/plugins/loading.js 4:25-61

ERROR in ./src/components/App.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue (/Users/ivan.liu/VIP文件/file/VIP-GULP/Project/git/vue-webpack/node_modules/vue/dist/vue.common.js:9095:8)
 @ ./src/app-src.js 2:10-41

ERROR in ./src/views/list/index.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue (/Users/ivan.liu/VIP文件/file/VIP-GULP/Project/git/vue-webpack/node_modules/vue/dist/vue.common.js:9095:8)
 @ ./src/common/js/router.config.js 34:12-50

ERROR in ./src/views/index/index.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue (/Users/ivan.liu/VIP文件/file/VIP-GULP/Project/git/vue-webpack/node_modules/vue/dist/vue.common.js:9095:8)
 @ ./src/common/js/router.config.js 19:12-51 26:12-51

**Comment by ivan403704409** [comment]
problem solved.
i forgot to install vue-loader....
