### ISSUE TITLE
How to use xxx.vue with slm ?（base on webpack）

### ISSUE THREAD

**Issue by noman798** [vuejs/vue#3414]
slm is this https://github.com/WealthBar/slm-loader

webpack config like this 

```

      {
            test: /\.vue\.slim$/,
            loaders: ["vue", "slm"]
      }

```

but webpack report error
```

ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/vue/app.vue.slim
Module build failed: TypeError: Cannot read property 'content' of undefined
at Object.module.exports (/home/dev/fund/node_modules/vue-loader/lib/selector.js:12:27)
@ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/vue/app.vue.slim 4:14-213

ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./src/vue/app.vue.slim
Module build failed: TypeError: Cannot read property 'content' of undefined
at Object.module.exports (/home/dev/fund/node_modules/vue-loader/lib/selector.js:12:27)
@ ./src/vue/app.vue.slim 3:17-185

ERROR in ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!./src/vue/app.vue.slim
Module build failed: TypeError: Cannot read property 'content' of undefined
at Object.module.exports (/home/dev/fund/node_modules/vue-loader/lib/selector.js:12:27)
@ ./src/vue/app.vue.slim 8:19-132
```

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
