### ISSUE TITLE
[2.0] [Suggestion] Warn on empty bindings when compiling

### ISSUE THREAD

**Issue by Async0x42** [vuejs/vue#3671]
I think that when binding a prop, if we forget to enter anything (i.e :col-key=""), then a warning should be displayed when compiling. (single file components).

Right now it gives a fairly non-descript exception being thrown (the line number doesn't point to where the root problem was)

` 
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-38!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/charts/OverallViewSingleStat.vue                                                                      
Module build failed: SyntaxError: Unexpected token (63:17)   
   at Parser.pp$3.parseExprSubscripts (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1749:23)                                                                                                      
    at Parser.pp$3.parseMaybeUnary (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1726:21)                                                                                                          
    at Parser.pp$3.parseExprOps (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1671:23)                                                                                                             
    at Parser.pp$3.parseMaybeConditional (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1654:23)                                                                                                    
    at Parser.pp$3.parseMaybeAssign (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1631:23)                                                                                                         
    at Parser.pp$3.parsePropertyValue (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:2032:91)                                                                                                       
    at Parser.parseObj (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:3919:16)                                                                                                                      
    at Parser.pp$3.parseExprAtom (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1839:21)                                                                                                            
    at Parser.parseExprAtom (P:\Wor\node_modules\vue-template-es2015-compiler\buble.js:3824:26)                                                                                                                 
    at Parser.pp$3.parseExprSubscripts (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1749:23)                                                                                                      
    at Parser.pp$3.parseMaybeUnary (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1726:21)                                                                                                          
    at Parser.pp$3.parseExprOps (P:\Work\node_modules\vue-template-es2015-compiler\buble.js:1671:23)                                                                                                             
 @ ./src/components/charts/OverallViewSingleStat.vue 7:23-155`

**Comment by posva** [comment]
I'm not sure to understand what you mean.
Warnings are only available on dev builds. Currently you have a warning when not giving a required prop.
Can you provide an example on a jsfiddle, please?

**Comment by Async0x42** [comment]
It is a dev build as far as I know, running locally w/ the webpack template (vue-cli). It throws this error during the server load (or hot reload). Is that able to be reproduced using jsfiddle?

A simple jsfiddle does give an error that it failed to compile the template: https://jsfiddle.net/1s962bo0/ , but obviously very different from the webpack dev server error. (I modified my spa to use the jsfiddle code, and it also compiles to an error as written in the original post)

**Comment by posva** [comment]
You should open an issue on `vue-loader` repo to request that feature. With webpack and vue-loader templates are compiled. That's when it's failing

**Comment by Async0x42** [comment]
Ah right, thanks!
