### ISSUE TITLE
execute "npm run build" failure.

### ISSUE THREAD

**Issue by huobaiyu** [vuejs/vue#3825]
got the following error message:
\vue\build\build.js:18
let builds = require('./config').getAllBuilds()
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by egoist** [comment]
try using node 5 or 6

**Comment by fnlctrl** [comment]
↑ As @egoist said.
