### ISSUE TITLE
Uncaught (in promise) TypeError: (intermediate value) is not a function 

### ISSUE THREAD

**Issue by sdyk-jym** [vuejs/vue#4045]
### Vue.js version
2.0.1
### vue-router version
2.0.0
### webpack version，node version
1.13.2 , 6.6.0

### Steps to reproduce
`Uncaught (in promise) TypeError: (intermediate value) is not a function
    at initData (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1228:5)
    at initState (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1182:3)
    at VueComponent.Vue._init (eval at <anonymous> (http://localhost:8080/app.js:600:2),<anonymous>:2508:5)
    at new VueComponent (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:3187:12)
    at createComponentInstanceForVnode (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1930:10)
    at init (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1935:31)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:2087:5)
    at createElm (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:3770:56)
    at VueComponent.patch [as __patch__] (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:4182:9)
    at VueComponent.Vue._update (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1689:19)`
   ` initData @ vue.common.js?a46a:1228
    initState @ vue.common.js?a46a:1182
    Vue._init @ vue.common.js?a46a:2508
    VueComponent @ vue.common.js?a46a:3187
    createComponentInstanceForVnode @ vue.common.js?a46a:1930
    init @ vue.common.js?a46a:1935
    (anonymous function) @ vue.common.js?a46a:2087
    createElm @ vue.common.js?a46a:3770
    patch @ vue.common.js?a46a:4182
    Vue._update @ vue.common.js?a46a:1689
    (anonymous function) @ vue.common.js?a46a:1662
    get @ vue.common.js?a46a:729
    run @ vue.common.js?a46a:798
    flushSchedulerQueue @ vue.common.js?a46a:616
    nextTickHandler @ vue.common.js?a46a:396`

大家好！
我正在用vue+vue-router做一个项目，项目进行了一周都没碰到过什么问题。
今天我在做项目的时候，新添加了一个组件，并给其配了相应的路由，然后发现不管是直接访问这个路径还是通过其它页面跳转到这个路径都会报上面这个错误，我仔细检查过路由的配置和组件代码，应该是没有问题的，eslint也没有检测到有语法错误。我在网上搜了好久，都没有发现解决办法。
所以各位前辈能否给点建议，看看从哪方面去入手来解决它。

使用vue-cli 构建的项目。

**Comment by fnlctrl** [comment]
> 新添加了一个组件，并给其配了相应的路由，然后发现不管是直接访问这个路径还是通过其它页面跳转到这个路径都会报上面这个错误

请检查这个组件。这个错误跟vue/vue-router毫无关系。
