### ISSUE TITLE
Recusive Local Components - Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cseufert** [vuejs/vue#4187]
### Vue.js version
1.0.28

### Reproduction Link

https://jsfiddle.net/25fdgLgr/3/

### Steps to reproduce
Just run new Vue() or let app demo app load

### What is Expected?
App loads as expected. (btw this does work in vue 2.0, but we are not quite ready to migrate the rest of our app.

### What is actually happening?
JS Error
vue.js:10148 Uncaught RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at createClass (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:10148:12)
    at Function.Vue.extend (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:10113:15)
    at guardComponents (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:1927:31)
    at mergeOptions (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:2004:3)
    at Function.Vue.extend (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:10117:19)
    at guardComponents (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:1927:31)
    at mergeOptions (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:2004:3)
    at Function.Vue.extend (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:10117:19)
    at guardComponents (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.js:1927:31)

**Comment by KingMario** [comment]
I'll try to resolve it.

**Comment by neobats** [comment]
Just noticed that this is marked 1.x, should it be closed? If not, has/should the PR be reviewed? Or am I missing something, which is likely.

**Comment by KingMario** [comment]
perhaps v1 is discontinued?
