### ISSUE TITLE
vue-server-renderer: createBundleRenderer() sourcemaps

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue#4421]
Hey!

Is there a way to pass in a sourcemap to `createBundleRenderer()`? There's an options argument, but it isn't documented (happy to write these docs if you point me towards the correct bit of source: I couldn't find it).

Currently, I'm getting this error, which isn't too understandable:

```
ReferenceError: window is not defined
    at e.__esModule.default (__vue_ssr_bundle__:1:478)
    at __vue_ssr_bundle__:1:1052
    at r.(anonymous function).exports (__vue_ssr_bundle__:1:146)
    at Object.<anonymous> (__vue_ssr_bundle__:1:285)
    at /Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-server-renderer/build.js:6152:21
    at runInVm (/Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-server-renderer/build.js:6144:10)
    at Object.renderToStream (/Users/callumacrae/Sites/samknows/website-vue/node_modules/vue-server-renderer/build.js:6175:9)
    at server.get (/Users/callumacrae/Sites/samknows/website-vue/server/index.js:29:35)
    at Layer.handle [as handle_request] (/Users/callumacrae/Sites/samknows/website-vue/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/callumacrae/Sites/samknows/website-vue/node_modules/express/lib/router/route.js:131:13)
```

**Comment by yyx990803** [comment]
It's currently not supported yet but on the roadmap.

**Comment by callumacrae** [comment]
Amazing! Just had to use git bisect to find the source of a bug.

Sorry for duplicate issue, searched the wrong words.
