### ISSUE TITLE
Server-side: Function type propare interpreted as String, not Function

### ISSUE THREAD

**Issue by shentao** [vuejs/vue#4871]
### Vue.js version
2.1.10

### Reproduction Link
https://github.com/shentao/vue-hackernews-2.0

### Steps to reproduce
1) Run the app
```
npm run dev
```

### What is Expected?
`<my-comp></my-comp>` should render to `<div>Default function result: value</div>`

### What is actually happening?
`<my-comp></my-comp>` throws error:
```
Vue warn]: Invalid prop: type check failed for prop "functionProp". Expected Function, got String. 
(found in component <my-comp> at /Users/damiandulisz/code/private/vue-hackernews-2.0/src/MyComp.vue)
Default function result: undefined
[Vue warn]: Error when rendering component <my-comp> at /Users/damiandulisz/code/private/vue-hackernews-2.0/src/MyComp.vue: 
error during render : /top
TypeError: _vm.functionProp is not a function
    at Proxy.render (__vue_ssr_bundle__:1605:48)
    at VueComponent.Vue._render (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue/dist/vue.runtime.common.js:2216:22)
    at renderComponent (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6078:25)
    at renderNode (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6061:7)
    at next (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6197:9)
    at next (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6189:7)
    at Object.cachedWrite [as write] (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at next (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6199:17)
    at cachedWrite (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at renderNode (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6069:7)
```

**Comment by posva** [comment]
so which one should we keep? 😛

**Comment by shentao** [comment]
Sorry! Not sure why GitHub saved the in-progress issue -_-
