### ISSUE TITLE
Vue 2.2.1+ compatibility with regard to Vue.util usage

### ISSUE THREAD

**Issue by karaoak** [vuejs/vue#5025]
As per release 2.2.0 of Vue (https://github.com/vuejs/vue/releases):

> Many exposed methods and properties on Vue.util have been removed. If you previously relied on them, you should migrate off of them since this object is intended for internal use only - it is not (and has never been) considered part of the public API and may change without notice in the future.

and because vue-validator 3 is using some Vue.util methods in many places, my Vue.js application compiled with Vue 2.2.1 is no longer working. it throws the following error:

> vue.common.js?e881:422 TypeError: resolveAsset is not a function
    at VueComponent._resolveValidator (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6019:1), <anonymous>:1476:12)
    at VueComponent.boundFn [as _resolveValidator] (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6026:1), <anonymous>:126:14)
    at VueComponent._getValidateRawDescriptor (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6019:1), <anonymous>:1484:22)
    at VueComponent.boundFn [as _getValidateRawDescriptor] (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6026:1), <anonymous>:125:14)
    at VueComponent._validate (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6019:1), <anonymous>:1680:27)
    at VueComponent.boundFn [as _validate] (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6026:1), <anonymous>:125:14)
    at eval (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6019:1), <anonymous>:1777:22)
    at Array.forEach (native)
    at VueComponent.validate (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6019:1), <anonymous>:1776:18)
    at VueComponent.boundFn [as validate] (eval at <anonymous> (http://k3.kifid.dev:5000/js/app.js:6026:1), <anonymous>:127:12)

When looking at the vue-validator 3.0 library Vue.util is used in many places.
Unfortunately I don't have the knowledge at this moment to create an alternatives for the Vue.util methods as used in your code. 

For this reason, I would like to ask you if this is a known issue and what the timeline could be to resolve :-) this issue.

Thanks for your great library.

**Comment by posva** [comment]
Hi Frank, this is actually an issue with vue-validator using Vue internals, there's nothing to do on Vue core but we are happy to review why some functions were used by some well used libraries like vue-validator and help them solve the compatibilities issues. The author of vue-validator being @kazupon we will probably discuss this directly.
Cheers 🙂

**Comment by karaoak** [comment]
Oeps, sorry, I posted my issue in the wrong repository. Sorry for this.
I was checking both Vue release notes and the vue-validator github pages. I mixed things up when logging into Github. My Apologies.
