### ISSUE TITLE
weex debug    error  报错了

### ISSUE THREAD

**Issue by cky113999742** [vuejs/vue#5335]
Vue packages version mismatch:

- vue@2.2.4
- vue-template-compiler@2.2.6

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/cuikeyi/.xtoolkit/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cuikeyi/.xtoolkit/node_modules/weex-vue-loader/lib/parser.js:2:16)
    at Module._compile (module.js:571:32)

**Comment by nicklv** [comment]
在/vue-template-compiler/index.js文件里面注释掉抛出异常的语句就行了，
