### ISSUE TITLE
使用vue-cli创建默认工程，不能启动dev

### ISSUE THREAD

**Issue by freshpassport** [vuejs/vue#5369]
node build/dev-server.js

> Starting dev server...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1270:14)
    at listen (net.js:1306:10)
    at Server.listen (net.js:1397:7)
    at Function.listen (/Users/mac/git/iview1/node_modules/.4.15.2@express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/mac/git/iview1/build/dev-server.js:82:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

**Comment by freshpassport** [comment]
找到问题了，是其他服务占用了8080端口。
