### ISSUE TITLE
Template.head() is not a function

### ISSUE THREAD

**Issue by sethdorris** [vuejs/vue#5634]
### Version
2.3.2

### Reproduction link
[https://github.com/sethdorris/fantasymx](https://github.com/sethdorris/fantasymx)

### Steps to reproduce
It's just better if you clone my repo to try it.... 

1. run the build script `npm run build`
2. start the app `npm run start`

the error is thrown with a shitty stack trace (see what is actually happening)

so I'm not sure if this is an error on my setup or not..

### What is expected?
Expecting my server to server index.html

### What is actually happening?
getting thrown the error

```
TypeError: template.head is not a function
    at TemplateRenderer.renderSync (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:1976:16)
    at RenderContext.done (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5701:39)
    at RenderContext.next (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:2169:17)
    at RenderContext.next (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:2186:12)
    at RenderContext.cachedWrite [as write] (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:1646:9)
    at RenderContext.next (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:2180:14)
    at RenderContext.cachedWrite [as write] (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:1646:9)
    at RenderContext.renderNode (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5412:15)
    at RenderContext.next (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:2177:14)
    at cachedWrite (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:1646:9)
    at renderElement (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5553:5)
    at renderNode (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5405:7)
    at renderComponentInner (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5522:3)
    at renderComponent (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5486:5)
    at renderNode (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5402:5)
    at render (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5655:5)
    at Object.renderToString (/Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:5699:9)
    at /Users/Seth/Projects/fantasymx/node_modules/vue-server-renderer/build.js:6006:22
```

**Comment by sethdorris** [comment]
This error is generated when code fails to pass in 'utf-8' to the fs.readFileSync method when using templates.

**Comment by industral** [comment]
Reading as `utf-8` fix that issue. Thanks @sethdorris!

```const template = fs.readFileSync('./index.html', 'utf-8');```
