### ISSUE TITLE
vue ssr和webpack配合使用，当配置了chunkFilename之后，报错

### ISSUE THREAD

**Issue by suifengfengye** [vuejs/vue#5637]
webpack的输出配置(客户端)：
```javascript
output: {
        path: path.resolve(__dirname, '../dist'),
        publicPath: `/${config.name}/dist/`,
        filename: 'js/[name].js',
        chunkFilename: 'js/[name].chunk.[chunkhash:6].js'
    }
```
webpack的输出配置（服务端）：
```javascript
output: {
        path: path.resolve(__dirname, '../dist'),
        publicPath: `/${config.name}/dist/`,
        filename: 'server-bundle.js',
        libraryTarget: 'commonjs2'
        chunkFilename: 'js/[name].chunk.[chunkhash:6].js'
    }
```
报错如下：
```
[vue-router] Failed to resolve async component default: Error: Cannot find module 'js\report.chunk.90dd42.js'
[vue-router] uncaught error during route navigation:
{ Error: Cannot find module 'js\report.chunk.90dd42.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (E:\work2\connecterp-web-nodejs\node_modules\vue-server-renderer\build.js:6964:16)
    at Function.requireEnsure [as e] (server-bundle.js:41:25)
    at report (server-bundle.js:1902:32)
    at E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1965:17
    at E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1992:66
    at Array.map (native)
    at E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1992:38
    at Array.map (native)
    at flatMapComponents (E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1991:26)
    at E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1930:5
    at iterator (E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1735:7)
    at step (E:\work2\connecterp-web-nodejs\node_modules\vue-router\dist\vue-router.common.js:1618:9) code: 'MODULE_NOT_FOUND' }
[vue-router] Failed to resolve async component default: Error: Cannot find module 'js\report.chunk.90dd42.js'

```

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by songyazhao** [comment]
我也遇到了这样的问题，我使用的是 **nuxt**
```bash
 ROUTE  /

  Error: Cannot find module 'pages_index.js?v=c439322c03f3e09ad94f' from 'E:\GitRepo-Doumi\doumi_vip_web'

  - sync.js:42 Function.module.exports [as sync]
    [doumi_vip_web]/[resolve]/lib/sync.js:42:15

  - build.js:8332 r
    [doumi_vip_web]/[vue-server-renderer]/build.js:8332:44

  - server-bundle.js:41 Function.requireEnsure [as e]
    server-bundle.js:41:25

  - server-bundle.js:4276 _d05de9d0
    server-bundle.js:4276:45

  - server-bundle.js:879 __WEBPACK_IMPORTED_MODULE_1_E_GitRepo_Doumi_doumi_vip_web_node_modules_babel_runtime_core_js_promise___default.a.all.flatMapComponents
    server-bundle.js:879:25

  - server-bundle.js:870
    server-bundle.js:870:14

  - Array.map

  - server-bundle.js:869
    server-bundle.js:869:143

  - Array.map

  - server-bundle.js:868 flatMapComponents
    server-bundle.js:868:57

  - server-bundle.js:876 resolveRouteComponents
    server-bundle.js:876:127

  - server-bundle.js:887 getRouteData
    server-bundle.js:887:9

  - server-bundle.js:967 setContext
    server-bundle.js:967:48

  - server-bundle.js:2959 createApp
    server-bundle.js:2959:76

  - server-bundle.js:2589 module.exports.__webpack_exports__.default
    server-bundle.js:2589:107

  - build.js:8426
    [doumi_vip_web]/[vue-server-renderer]/build.js:8426:15
```

**Comment by songyazhao** [comment]
Relevant issues: #5637, [nuxt.js#3331](https://github.com/nuxt/nuxt.js/issues/3331)
