### ISSUE TITLE
Cant install in windows 7 after this commit b5f08f3bed95e6cac47b20d3fa4148d00ffa8c55

### ISSUE THREAD

**Issue by kasselTrankos** [vuejs/vue#6090]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/1x5yfnkf/](https://jsfiddle.net/1x5yfnkf/)

### Steps to reproduce
cmd
npm init -y
npm i -S vue

### What is expected?
Correct installation of vue from npm

### What is actually happening?
This error:
C:\node-scripts\pine>npm i -D vue

> vue@2.4.0 postinstall C:\node-scripts\pine\node_modules\vue
> node build/install-hooks.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\node-scripts\pine\node_modules\vue\build\install-hooks.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})
npm WARN pine@1.0.0 No description
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "vue"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! vue@2.4.0 postinstall: `node build/install-hooks.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue@2.4.0 postinstall script 'node build/install-hooks.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/install-hooks.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node-scripts\pine\npm-debug.log

---
windows 7
C:\node-scripts\pine>npm -v
3.10.10

C:\node-scripts\pine>node -v
v6.9.5

**Comment by jkzing** [comment]
Should be fixed in [https://github.com/vuejs/vue/releases/tag/v2.4.1](https://github.com/vuejs/vue/releases/tag/v2.4.1).

**Comment by kasselTrankos** [comment]
Thanks, qucly solution . GREAT
Can i, make npm and not download.

**Comment by JounQin** [comment]
Just upgrade to 2.4.1

**Comment by kasselTrankos** [comment]
I've review the historic of changes of pacjkage, and saw that error is previos of this revisio, and i expect will be inside, try itand tell us.

**Comment by kasselTrankos** [comment]
Yes it solved using 2.4.1, using: 
npm -i -S vue@2.4.1 

t solved. Great!!!

**Comment by kasselTrankos** [comment]
Hi, 
When i was compiling got this error :
 [0] C:\node-scripts\pine\node_modules\vue-template-compiler\index.js:8
[0]   throw new Error(
[0]   ^
[0]
[0] Error:
[0]
[0] Vue packages version mismatch:
[0]
[0] - vue@2.4.1
[0] - vue-template-compiler@2.4.0
[0]
[0] This may cause things to work incorrectly. Make sure to use the same version for both.
[0] If you are using vue-loader@>=10.0, simply update vue-template-compiler.
[0] If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
[0]
[0]     at Object.<anonymous> (C:\node-scripts\pine\node_modules\vue-template-compiler\index.js:8:9)
[0]     at Module._compile (module.js:570:32)
[0]     at Object.Module._extensions..js (module.js:579:10)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (C:\node-scripts\pine\node_modules\vueify\lib\compiler.js:6:19)

so to solve it you must uninstall vue-template-compiler and reinstall vit , but version 2.4.1. Same as vue

> npm uninstall -S vue-template compiler
> npm i -S vue-template-compiler@2.4.1

Now its completed solved, installation and compilation.

Thanks to all.

**Comment by kasselTrankos** [comment]
take it as closed issue
