### ISSUE TITLE
vue-cli 即使是新项目  热修改样式文件报错

### ISSUE THREAD

**Issue by Axulai** [vuejs/vue#6197]
#vue init webpack
#npm i 
#npm run dev
给任意地方的css加一个任意改动，甚至是换行  控制台立马报错：

 WAIT  Compiling...                                                                                                                                         6:54:53 PM

/Users/yinxulai/Desktop/Design.js/mactnt/node_modules/_enhanced-resolve@3.4.0@enhanced-resolve/lib/CachedInputFileSystem.js:145
                        if(key.startsWith(what))
                              ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/yinxulai/Desktop/Design.js/mactnt/node_modules/_enhanced-resolve@3.4.0@enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/yinxulai/Desktop/Design.js/mactnt/node_modules/_enhanced-resolve@3.4.0@enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/yinxulai/Desktop/Design.js/mactnt/node_modules/_enhanced-resolve@3.4.0@enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at EventEmitter.watcher.once (/Users/yinxulai/Desktop/Design.js/mactnt/node_modules/_webpack@2.7.0@webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (/Users/yinxulai/Desktop/Design.js/mactnt/node_modules/_watchpack@1.4.0@watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mactnt@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1

**Comment by yyx990803** [comment]
这是 webpack 一个内部依赖更新导致的问题，要等他们修复了

**Comment by palmerye** [comment]
This problem has been resolved in the latest version of enhanced-resolve@3.4.1,
you can do this:
`npm install enhanced-resolve@latest`
