### ISSUE TITLE
vue-server-renderer file sync resolve webfont support query string

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue#7519]
### What problem does this feature solve?
element-ui custom theme, scss font file using the query string, resulting in the failure to load the file when use npm package `resolve`.

It report error:

`{ Error: Cannot find module 'element-ui/lib/theme-chalk/fonts/element-icons.woff?t=1510834658947' from 'D:\source-control\git\ydmap-ssr-portal'
    at Function.module.exports [as sync] (D:\source-control\git\ydmap-ssr-portal\node_modules\vue-server-renderer\node_modules\resolve\lib\sync.js:40:15)
    at r (D:\source-control\git\ydmap-ssr-portal\node_modules\vue-server-renderer\build.js:8149:44)
    at Object.<anonymous> (webpack:/external "element-ui/lib/theme-chalk/fonts/element-icons.woff:1:0)`

see element-ui issue [here](https://github.com/ElemeFE/element/issues/9086)

I'm not sure who should handle this issue.

### What does the proposed API look like?
N/A

**Comment by yyx990803** [comment]
This is not a feature request.

**Comment by summertian4** [comment]
This is because  wrong path.
You should put the style folder in this path:
```
node_modules/element-ui/lib/theme-chalk
```
