### ISSUE TITLE
Error in nextTick: "TypeError: Cannot read property 'createElement' of undefined"

### ISSUE THREAD

**Issue by akicho8** [vuejs/vue#7522]
### Version
2.5.13

### Reproduction link
[https://github.com/akicho8/vue-hello-app](https://github.com/akicho8/vue-hello-app)

### Steps to reproduce
```
git clone https://github.com/akicho8/vue-hello-app
cd vue-hello-app
yarn
yarn test
```

### What is expected?
There is no error message

### What is actually happening?
I get an error

```
$ yarn test
yarn run v1.3.2
warning package.json: No license field
$ npm run unit

> vue-hello-app@0.0.1 unit /path/to/vue-hello-app
> jest --config test/unit/jest.conf.js

 PASS  test/unit/specs/App.spec.js
  App
    ✓ render (20ms)

  console.error node_modules/vue/dist/vue.runtime.common.js:576
    [Vue warn]: Error in nextTick: "TypeError: Cannot read property 'createElement' of undefined"

  console.error node_modules/vue/dist/vue.runtime.common.js:1715
    TypeError: Cannot read property 'createElement' of undefined
        at Object.createElement$1 [as createElement] (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:5235:22)
        at createElm (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:5481:19)
        at updateChildren (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:5747:11)
        at patchVnode (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:5838:29)
        at VueComponent.patch [as __patch__] (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:5998:9)
        at VueComponent.Vue._update (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:2645:19)
        at VueComponent.updateComponent (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:2763:10)
        at Watcher.get (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:3113:25)
        at Watcher.run (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:3190:22)
        at flushSchedulerQueue (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:2952:13)
        at Array.<anonymous> (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:1811:12)
        at flushCallbacks (/path/to/vue-hello-app/node_modules/vue/dist/vue.runtime.common.js:1732:14)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:160:7)
```

---
```
<template>
<div>
  <div v-if="foo">
  </div>
</div>
</template>

<script>
import axios from "axios"

export default {
  data() {
    return {
      foo: null,
    }
  },

  created() {
    axios.get("http://google.co.jp/").then((r) => {
    }).catch((error) => {
      this.foo = true
    })
  },
}
</script>
```

There is no error when commenting out `this.foo = true`

I do not know whether it is faulty or how I used it incorrectly.

**Comment by posva** [comment]
Mounting components with no `document` will not work. If you want to properly test Vue components, I recommend you to check https://vue-test-utils.vuejs.org/
If you want render components on a server (with no `document`), you should check https://ssr.vuejs.org

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
