### ISSUE TITLE
vue create project error

### ISSUE THREAD

**Issue by pbaiyy** [vuejs/vue#8333]
### Version
2.5.16

### Reproduction link
[http://www](http://www)

### Steps to reproduce
vue init webpack a

### What is expected?
module.js:549
    throw err;
    ^

Error: Cannot find module 'rc'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\vue-cli\node_modules\get-proxy\index.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

### What is actually happening?
create project fail

**Comment by ulivz** [comment]
Perhaps this issue should be transferred to [vue-cli](https://github.com/vuejs/vue-cli), furthermore, please provide the version of vue-cli and your os, thanks!

**Comment by sodatea** [comment]
Closed due to wrong repository and lack of necessary information.

------

BTW, it could be a network problem during initialization, based on my experience.
