### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by castilh0s** [vuejs/vue#8453]
### Version
2.5.16

### Reproduction link
[I can't create a minimal reproduction](https://codepen.io)

### Steps to reproduce
I don't know how to reproduce that, it appears sometimes when I reload a page, and I can't create a minimal reproduction...

### What is expected?
Expects the page reload normally.

### What is actually happening?
Sometimes while page is reloading, this error appears in the browser:
![Captura de tela de 2018-07-03 14-44-15.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/bacb53c0-7ee8-11e8-9857-1d1742c00ee5.png)

And this error appears in the console:
```
at Object.<anonymous> (.nuxt/server.js:1:0)
at __webpack_require__ (webpack:/webpack/bootstrap 9148d4a2990df53d293e:25:0)
at server-bundle.js:92:18
at Object.<anonymous> (server-bundle.js:95:10)
at evaluateModule (/PROJECT_FOLDER/node_modules/vue-server-renderer/build.js:8338:21)
at /PROJECT_FOLDER/node_modules/vue-server-renderer/build.js:8396:18
at new Promise (<anonymous>)
at /PROJECT_FOLDER/node_modules/vue-server-renderer/build.js:8388:14
at Object.renderToString (/PROJECT_FOLDER/node_modules/vue-server-renderer/build.js:8564:9)
at Renderer.renderRoute (/PROJECT_FOLDER/node_modules/nuxt/lib/core/renderer.js:344:41)
at Renderer.nuxtMiddleware (/PROJECT_FOLDER/node_modules/nuxt/lib/core/middleware/nuxt.js:12:31)
at call (/PROJECT_FOLDER/node_modules/connect/index.js:239:7)
at next (/PROJECT_FOLDER/node_modules/connect/index.js:183:5)
at SendStream.error (/PROJECT_FOLDER/node_modules/serve-static/index.js:121:7)
at emitOne (events.js:116:13)
at SendStream.emit (events.js:211:7)
at SendStream.error (/PROJECT_FOLDER/node_modules/send/index.js:270:17)
at SendStream.onStatError (/PROJECT_FOLDER/node_modules/send/index.js:421:12)
at next (/PROJECT_FOLDER/node_modules/send/index.js:736:16)
at onstat (/PROJECT_FOLDER/node_modules/send/index.js:725:14) statusCode: 500, name: 'TypeError' }
```

---
This error appeared a week ago and since then I can't found a cause for it.

**Comment by posva** [comment]
We need a minimal reproduction. you can try using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
