### ISSUE TITLE
bundle export should be a function when using { runInNewContext: false }

### ISSUE THREAD

**Issue by pirmax** [vuejs/vue#8481]
### Version
2.5.16

### Reproduction link
[https://github.com/pirmax/nuxt-and-nest](https://github.com/pirmax/nuxt-and-nest)

### Steps to reproduce
You need NestJS, NuxtJS and Vue.

### What is expected?
When I go to the NuxtJS page, I get this error:

```{ Error: bundle export should be a function when using { runInNewContext: false }.
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8401:17
    at new Promise (<anonymous>)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8564:9)
    at Renderer.renderRoute (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/renderer.js:344:41)
    at Renderer.nuxtMiddleware (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/middleware/nuxt.js:12:31)
    at call (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:239:7)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:183:5)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:421:12)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:764:28)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:772:23
    at FSReqWrap.oncomplete (fs.js:152:21) statusCode: 500, name: 'NuxtServerError' }```

When I refresh page, the error is not the same:

```{ TypeError: runner is not a function
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8426:15
    at new Promise (<anonymous>)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8564:9)
    at Renderer.renderRoute (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/renderer.js:344:41)
    at Renderer.nuxtMiddleware (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/middleware/nuxt.js:12:31)
    at call (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:239:7)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:183:5)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:421:12)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:764:28)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:772:23
    at FSReqWrap.oncomplete (fs.js:152:21) statusCode: 500, name: 'TypeError' }```

### What is actually happening?
Error on page:

`bundle export should be a function when using { runInNewContext: false }.`

Error on refreshed page:

`runner is not a function`

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by posva** [comment]
That's way too much for a repro. Please make sure the problem doesn't come from the other libraries first, if it's not, create a boiled down repro  (no next, no nest). Il

**Comment by pirmax** [comment]
Reproduction is very easy to set up.

It does not come from other libraries! I have already tried to install only NuxtJS with Vue. This comes from **vue-server-renderer** which is managed by Vue!

So thank you for taking this request into account!
