### ISSUE TITLE
DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by xiaomingdexian** [vuejs/vue#8482]
### Version
2.5.16

### Reproduction link
[http://jsfiddle.net/tb4sap2c/3/](http://jsfiddle.net/tb4sap2c/3/)

### Steps to reproduce
open the url

### What is expected?
no error

### What is actually happening?
exception be thrown

---
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insertBefore (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:5325:14)
    at updateChildren (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:5838:32)
    at patchVnode (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:5923:29)
    at VueComponent.patch [as __patch__] (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:6083:9)
    at VueComponent.Vue._update (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2670:19)
    at VueComponent.updateComponent (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2788:10)
    at Watcher.get (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:3140:25)
    at Watcher.run (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:3217:22)
    at flushSchedulerQueue (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2981:13)
    at Array.<anonymous> (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1839:12)

**Comment by Justineo** [comment]
Please provide a simple reproduction that doesn't include such third party library. The fiddle you've provided is offering too much information. Issues here are just for bugs/feature requests for Vue.js itself, not for seeking free help on debugging any app using Vue.js.

**Comment by posva** [comment]
You can use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions. But feel free to come back and open an issue if it turns out to be a bug  (with a boiled down repro) 🙂

**Comment by xiaomingdexian** [comment]
@Justineo , @posva

I'm sorry I use the issues in the wrong way.
Thank you for your reply.
