### ISSUE TITLE
[vue-server-renderer] Bug failing when using a reference of process - related to SSRClientWebpackPlugin

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue#9194]
### Version
2.5.21

### Reproduction link
[https://github.com/AlexandreBonaventure/repro-vue-ssr-bug](https://github.com/AlexandreBonaventure/repro-vue-ssr-bug)

### Steps to reproduce
1. `yarn install`
2. `yarn run ssr:build && yarn ssr:start`
3. go to localhost:8000

### What is expected?
to serve / correctly

### What is actually happening?
error 500:
```
TypeError: Cannot read property 'replace' of undefined
    at normalizeFile (.../node_modules/vue-server-renderer/build.js:8183:27)
```

---
Hi, I came across this weird bug when I was trying to retrieve a global variable (eg. global.localenv.PUBLIC_URL) in App.vue to populate a meta tag (using vue-meta).
I stumble upon the bug, and narrowed it down to referencing `process` being the cause here.
Another weird thing is that if you remove the component Icons import in the minimal repro, it works fine!

The error stack is initiated by `TemplateRenderer.renderPreloadLinks` which makes me think that maybe it is a bug in the webpack SSRClientPlugin which inject preload links for every assets.

**Comment by tkjaergaard** [comment]
+1 

I'm experiencing the same issue `TypeError: Cannot read property 'replace' of undefined`. I have not narrowed down what causes this in my application, but I'll do some digging.

**Comment by chentianyuan** [comment]
same error here

**Comment by Zacaria** [comment]
Same error here since five days, this morning magically disappeared :thinking:

**Comment by chentianyuan** [comment]
> same error here

fix it, maybe will should put VueSSRClientPlugin in a right place

**Comment by EDiaos** [comment]
I got the new error on vue-ssr-renderer 2.6.6 
```
TypeError: Cannot read property 'replace' of undefined
    at fo (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:72913)
    at Array.map (<anonymous>)
    at lo.getUsedAsyncFiles (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:76029)
    at lo.getPreloadFiles (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:74209)
    at lo.renderPreloadLinks (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:74362)
    at lo.renderResourceHints (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:74106)
    at lo.render (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:73571)
    at yt.done (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:79374)
    at yt.next (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:20272)
    at yt.n [as write] (/Volumes/Disk/github/vue-cli3-ssr-project/node_modules/vue-server-renderer/build.prod.js:1:18596)
```

**Comment by sebastianks** [comment]
I had this error too when building my client webpack config. It turns out that I forgot to delete `VueSSRServerPlugin()` and had both the server and client plugin. As soon as I removed the server plugin from the client config it works.

I am not sure if it's related but someone else might have the same issue.

**Comment by laure-at-irun** [comment]
For me, the error was caused by a malformed `vue-ssr-client-manifest.json` : in the modules section, some modules were mapped to indexes `-1`. As a result, at runtime, the `vue-server-renderer` was unable to load the file. 

To fix it, I just enabled the source maps for css files. In `vue.config.js`, add to your client config : 

```js
css: {
     sourceMap: true,
},
```

I hope this will help.

**Comment by AlexandreBonaventure** [comment]
@laure-at-irun  yep! that was my issue as well

**Comment by OliverJEvans** [comment]
@laure-at-irun This fixed the issue for me too. But why!?

**Comment by irun-devel** [comment]
The vue client plugin receives from webpack compilation stats a list of files that includes css maps, even when css maps are not emitted. The list is provided by webpack though [stats.chunks.files](https://webpack.js.org/api/stats/#chunk-objects). The [stats.assets](https://webpack.js.org/api/stats/#asset-objects) doesn't contain the css map files.

However, I am not sure why webpack is doing this. 

Anyway, the client plugin is not robust to webpack inconsistent data.

**Comment by laure-at-irun** [comment]
The vue client plugin receives from webpack compilation stats a list of files that includes css maps, even when css maps are not emitted. The list is provided by webpack though [stats.chunks.files](https://webpack.js.org/api/stats/#chunk-objects). The [stats.assets](https://webpack.js.org/api/stats/#asset-objects) doesn't contain the css map files.

However, I am not sure why webpack is doing this. 

Anyway, the client plugin is not robust to webpack inconsistent data.

**Comment by lovetingyuan** [comment]
https://github.com/vuejs/vue/issues/9488#issuecomment-514985110

**Comment by lovetingyuan** [comment]
> The vue client plugin receives from webpack compilation stats a list of files that includes css maps, even when css maps are not emitted. The list is provided by webpack though [stats.chunks.files](https://webpack.js.org/api/stats/#chunk-objects). The [stats.assets](https://webpack.js.org/api/stats/#asset-objects) doesn't contain the css map files.
> 
> However, I am not sure why webpack is doing this.
> 
> Anyway, the client plugin is not robust to webpack inconsistent data.

Maybe souceMap in chunks is set by option: `devtool`.
