### ISSUE TITLE
Object Rest/Spread is not fully supported in templates yet?

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#9460]
### Version
2.6.3

~~### Reproduction link~~

### Steps to reproduce
```vue
<template>
  <Test>
    <template v-slot="{ foo, ...props }">
      <div>{{ foo }}</div>
      <pre>{{ props }}</pre>
    </template>
  </Test>
</template>

<script>
  export default {
    name: 'App',
    components: {
      Test: {
        render(h) {
          return h('div', this.$scopedSlots.default({
            foo: 'foo',
            bar: true,
          }))
        }
      }
    }
  }
</script>
```

[On vue 2.6 project's board](https://github.com/vuejs/vue/projects/4#card-15495648) there is listed support for object spread syntax in templates. It says it's enabled in vue-template-es2015-compiler@1.8, which latest version of vue-loader (15.6.2) is already using. I just created test project using vue-cli. There's ineed vue-template-es2015-compiler@1.8.2 installed in my node_modules directory, but above reproduction still does not work.

### What is expected?
Object rest spread should work in templates

### What is actually happening?
When attempting to compile above component, this error is being thrown:

```
./src/components/HelloWorld.vue?vue&type=template&id=469af010& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"16addc27-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=template&id=469af010&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
TypeError: Cannot read property 'line' of undefined
    at getSnippet (C:\dev\vue-cli-app\node_modules\vue-template-es2015-compiler\buble.js:6077:28)
    at Object.transform (C:\dev\vue-cli-app\node_modules\vue-template-es2015-compiler\buble.js:14103:17)
    at transpile (C:\dev\vue-cli-app\node_modules\vue-template-es2015-compiler\index.js:23:20)
    at actuallyCompile (C:\dev\vue-cli-app\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:86:20)
    at compileTemplate (C:\dev\vue-cli-app\node_modules\@vue\component-compiler-utils\dist\compileTemplate.js:28:16)
    at Object.module.exports (C:\dev\vue-cli-app\node_modules\vue-loader\lib\loaders\templateLoader.js:46:20)
```

**Comment by yyx990803** [comment]
The support was for creating objects with spread, as in `v-bind="{ a, ...b }"`. Spread destructuring is actually a separate feature. Please open an issue in `vue-template-es2015-compiler`'s repo.
