### ISSUE TITLE
Possible regression of #8545 Maximum call stack size exceeded in SSR with a v-for with 1000 components

### ISSUE THREAD

**Issue by daleconboy** [vuejs/vue#9562]
### Version
2.6.7

### Reproduction link
[https://github.com/daleconboy/vue-reduction](https://github.com/daleconboy/vue-reduction)

### Steps to reproduce
1. Clone the reproduction repo
1. Use Node >= 8.0.0
1. `npm install`
1. `npm run vue`

### What is expected?
The script should complete successfully and should log a long string of html to your terminal.

### What is actually happening?
An error is thrown:

```
RangeError: Maximum call stack size exceeded
    at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3527:7)
    at resolve (node_modules/vue-server-renderer/build.dev.js:8366:27)
    at waitForServerPrefetch (node_modules/vue-server-renderer/build.dev.js:8238:3)
    at renderComponentInner (node_modules/vue-server-renderer/build.dev.js:8377:3)
    at renderComponent (node_modules/vue-server-renderer/build.dev.js:8334:5)
    at RenderContext.renderNode (node_modules/vue-server-renderer/build.dev.js:8245:5)
    at RenderContext.next (node_modules/vue-server-renderer/build.dev.js:2597:23)
    at cachedWrite (node_modules/vue-server-renderer/build.dev.js:2450:9)
    at renderElement (node_modules/vue-server-renderer/build.dev.js:8485:5)
    at renderNode (node_modules/vue-server-renderer/build.dev.js:8247:5)
```

**Comment by daleconboy** [comment]
Link to the original issue: #8545
