### ISSUE TITLE
SSR在dev模式下失败，production可以运行

### ISSUE THREAD

**Issue by silverPanda** [vuejs/vue#9987]
刚刚vue 和 vue-server-renderer 升级到 2.6.10 结果发现在production模式下可以运行，但是在development模式下会报这个错
```code
15:53:55 79|APP  | [2019-05-07T15:53:55.768] [ERROR] koa - ReferenceError: self is not defined
15:53:55 79|APP  |     at Object.<anonymous> ((webpack)-dev-server/client:245:0)
15:53:55 79|APP  |     at Object../node_modules/webpack-dev-server/client/index.js?http://localhost:13002 (main.js:1217:30)
15:53:55 79|APP  |     at __webpack_require__ (webpack/bootstrap:19:0)
15:53:55 79|APP  |     at Object.0 (main.js:1989:1)
15:53:55 79|APP  |     at __webpack_require__ (webpack/bootstrap:19:0)
15:53:55 79|APP  |     at main.js:85:18
15:53:55 79|APP  |     at Object.<anonymous> (main.js:88:10)
15:53:55 79|APP  |     at evaluateModule (/home/leo/Apps/apps-mobile-docs/node_modules/vue-server-renderer/build.dev.js:9303:21)
15:53:55 79|APP  |     at /home/leo/Apps/apps-mobile-docs/node_modules/vue-server-renderer/build.dev.js:9361:18
15:53:55 79|APP  |     at new Promise (<anonymous>)
15:53:55 79|APP  |     at /home/leo/Apps/apps-mobile-docs/node_modules/vue-server-renderer/build.dev.js:9353:14
15:53:55 79|APP  |     at Object.renderToString (/home/leo/Apps/apps-mobile-docs/node_modules/vue-server-renderer/build.dev.js:9529:9)
15:53:55 79|APP  |     at Promise (/home/leo/Apps/apps-mobile-docs/node_modules/@kso/koa-vue-server-renderer/lib/index.js:27:20)
15:53:55 79|APP  |     at new Promise (<anonymous>)
15:53:55 79|APP  |     at module.exports (/home/leo/Apps/apps-mobile-docs/node_modules/@kso/koa-vue-server-renderer/lib/index.js:26:18)
15:53:55 79|APP  |     at Object.ctx.renderer (/home/leo/Apps/apps-mobile-docs/node_modules/@kso/koa-vue-server-renderer/dev.js:25:34)
```

**Comment by silverPanda** [comment]
如果我降级到2.5.x配合vue-cli却又没有问题。。。
